version: '3'

services:

  postgres:
    image: postgres:11-alpine
    env_file:
      - .env
    volumes:
      - ./.docker-volumes/postgresql-data:/var/lib/postgresql/data
    expose:
      - '5432'

  api:
    build:
      context: ./server/
      dockerfile: ./compose/Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - STATIC_ROOT=/static
    expose:
      - '8000'
    volumes:
      - ./.docker-volumes/static:/static
    command: runserver.sh

  nginx:
    image: nginx:latest
    ports:
      - "8787:8000"
    volumes:
      - ./server/compose/nginx:/etc/nginx/conf.d
      - ./.docker-volumes/static:/static
    depends_on:
      - api
