# Production docker-compose file

version: '3'

services:

  postgres:
    image: postgres:11-alpine
    env_file:
      - .env
    volumes:
      - ./.docker-volumes/postgresql-data:/var/lib/postgresql/data
    expose:
      - '5432'

  api:
    build:
      context: ./server/
      dockerfile: ./compose/Dockerfile
    env_file:
      - .env
    environment:
      - STATIC_ROOT=/static
    expose:
      - '8000'
    volumes:
      - ./.docker-volumes/static:/static
    command: runserver.sh
    depends_on:
      - postgres

  spa:
    build:
      context: ./spa/
      args:
        REACT_APP_API_URL: http://localhost:8787/api/v1/
    env_file:
      - .env
    volumes:
      - ./.docker-volumes/spa_index:/index
      - ./.docker-volumes/static:/static

  nginx:
    image: nginx:latest
    ports:
      - '8787:8000'
    volumes:
      - ./compose/nginx:/etc/nginx/conf.d
      - ./.docker-volumes/spa_index:/spa_index
      - ./.docker-volumes/static:/static
    depends_on:
      - api
      - spa
