# Run tests in docker

version: '3'

services:

  postgres:
    image: postgres:11-alpine
    expose:
      - '5432'
    volumes:
      - ./.docker-volumes/test/postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app

  test:
    build:
      context: .
      dockerfile: ./compose/test.Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - SECRET_KEY=testing-secret-key

    command: run_tests.sh
