# Generated by Django 2.2.3 on 2019-07-03 01:08

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(db_index=True, max_length=128, verbose_name='Last name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('state', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], max_length=32, verbose_name='State')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('groups', models.ManyToManyField(related_name='members', through='users.GroupMembership', to='groups.Group')),
            ],
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
