# Generated by Django 2.2.3 on 2019-07-03 03:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190703_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], max_length=32, verbose_name='State'),
        ),
    ]
